//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_dlya_SKUD
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Админ.
    /// </summary>
    // *** Start programmer edit section *** (Админ CustomAttributes)

    // *** End programmer edit section *** (Админ CustomAttributes)
    [AutoAltered()]
    [Caption("Администратор")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АдминE", new string[] {
            "СпрСотр as \'Спр сотр\'",
            "СпрСотр.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "СпрСотр.ФИО"})]
    [MasterViewDefineAttribute("АдминE", "СпрСотр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("АдминL", new string[] {
            "СпрСотр.ФИО as \'ФИО\'"})]
    public class Админ : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Prilozhenie_dlya_SKUD.СпрСотр fСпрСотр;
        
        // *** Start programmer edit section *** (Админ CustomMembers)

        // *** End programmer edit section *** (Админ CustomMembers)

        
        /// <summary>
        /// Админ.
        /// </summary>
        // *** Start programmer edit section *** (Админ.СпрСотр CustomAttributes)

        // *** End programmer edit section *** (Админ.СпрСотр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрСотр"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_dlya_SKUD.СпрСотр СпрСотр
        {
            get
            {
                // *** Start programmer edit section *** (Админ.СпрСотр Get start)

                // *** End programmer edit section *** (Админ.СпрСотр Get start)
                IIS.Prilozhenie_dlya_SKUD.СпрСотр result = this.fСпрСотр;
                // *** Start programmer edit section *** (Админ.СпрСотр Get end)

                // *** End programmer edit section *** (Админ.СпрСотр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Админ.СпрСотр Set start)

                // *** End programmer edit section *** (Админ.СпрСотр Set start)
                this.fСпрСотр = value;
                // *** Start programmer edit section *** (Админ.СпрСотр Set end)

                // *** End programmer edit section *** (Админ.СпрСотр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АдминE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдминE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдминE", typeof(IIS.Prilozhenie_dlya_SKUD.Админ));
                }
            }
            
            /// <summary>
            /// "АдминL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АдминL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АдминL", typeof(IIS.Prilozhenie_dlya_SKUD.Админ));
                }
            }
        }
    }
}
