//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_dlya_SKUD
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Кар дос.
    /// </summary>
    // *** Start programmer edit section *** (КарДос CustomAttributes)

    // *** End programmer edit section *** (КарДос CustomAttributes)
    [AutoAltered()]
    [Caption("Кар дос")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КарДосE", new string[] {
            "НомерКарты as \'Номер карты\'",
            "Админ as \'Админ\'"})]
    [MasterViewDefineAttribute("КарДосE", "Админ", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [View("КарДосL", new string[] {
            "НомерКарты as \'Номер карты\'"})]
    public class КарДос : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерКарты;
        
        private IIS.Prilozhenie_dlya_SKUD.Админ fАдмин;
        
        // *** Start programmer edit section *** (КарДос CustomMembers)

        // *** End programmer edit section *** (КарДос CustomMembers)

        
        /// <summary>
        /// НомерКарты.
        /// </summary>
        // *** Start programmer edit section *** (КарДос.НомерКарты CustomAttributes)

        // *** End programmer edit section *** (КарДос.НомерКарты CustomAttributes)
        public virtual int НомерКарты
        {
            get
            {
                // *** Start programmer edit section *** (КарДос.НомерКарты Get start)

                // *** End programmer edit section *** (КарДос.НомерКарты Get start)
                int result = this.fНомерКарты;
                // *** Start programmer edit section *** (КарДос.НомерКарты Get end)

                // *** End programmer edit section *** (КарДос.НомерКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КарДос.НомерКарты Set start)

                // *** End programmer edit section *** (КарДос.НомерКарты Set start)
                this.fНомерКарты = value;
                // *** Start programmer edit section *** (КарДос.НомерКарты Set end)

                // *** End programmer edit section *** (КарДос.НомерКарты Set end)
            }
        }
        
        /// <summary>
        /// Кар дос.
        /// </summary>
        // *** Start programmer edit section *** (КарДос.Админ CustomAttributes)

        // *** End programmer edit section *** (КарДос.Админ CustomAttributes)
        [PropertyStorage(new string[] {
                "Админ"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_dlya_SKUD.Админ Админ
        {
            get
            {
                // *** Start programmer edit section *** (КарДос.Админ Get start)

                // *** End programmer edit section *** (КарДос.Админ Get start)
                IIS.Prilozhenie_dlya_SKUD.Админ result = this.fАдмин;
                // *** Start programmer edit section *** (КарДос.Админ Get end)

                // *** End programmer edit section *** (КарДос.Админ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КарДос.Админ Set start)

                // *** End programmer edit section *** (КарДос.Админ Set start)
                this.fАдмин = value;
                // *** Start programmer edit section *** (КарДос.Админ Set end)

                // *** End programmer edit section *** (КарДос.Админ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КарДосE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КарДосE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КарДосE", typeof(IIS.Prilozhenie_dlya_SKUD.КарДос));
                }
            }
            
            /// <summary>
            /// "КарДосL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КарДосL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КарДосL", typeof(IIS.Prilozhenie_dlya_SKUD.КарДос));
                }
            }
        }
    }
}
